using System.IO;
using System.Text.Json;
using PoeOverlay.Composition;
using Xunit;

namespace PoeOverlay.Shell.Tests.Overlay;

/// <summary>
/// The manifest that actually ships agrees with the icons that actually ship (S4 16.11).
/// </summary>
/// <remarks>
/// <para>
/// <c>tools/build-icon-manifest.py</c> checks the same things and refuses to write a manifest that
/// fails them, so this looks like a duplicate. It is not: the generator guards the moment the file
/// is <em>written</em>, and this guards every moment afterwards — a hand edit, a bad merge, a
/// half-applied league refresh that regenerated the names and not the icons.
/// </para>
/// <para>
/// It is also the only check that the build copies the icons at all. The PNGs are referenced out of
/// <c>data/images/</c> by a wildcard (HLD §9); a typo in that glob produces a build that succeeds
/// and an overlay with no pictures.
/// </para>
/// </remarks>
public sealed class ItemIconManifestTests
{
    private const string CardIcon = "DivinationCard.png";

    private static readonly string IconDirectory =
        Path.Combine(AppContext.BaseDirectory, ShellConstants.IconFolderName);

    private static readonly Lazy<Dictionary<string, string>> Manifest = new(() =>
    {
        var path = Path.Combine(IconDirectory, "item-icons.json");
        Assert.True(File.Exists(path), $"The icon manifest was not copied to the output: {path}");

        var entries = JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(path));
        Assert.NotNull(entries);
        return entries!;
    });

    [Fact]
    public void EveryIconTheManifestNames_WasCopiedBesideTheExecutable()
    {
        var missing = Manifest.Value.Values
            .Distinct(StringComparer.Ordinal)
            .Where(name => !File.Exists(Path.Combine(IconDirectory, name)))
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToList();

        Assert.Empty(missing);
    }

    [Fact]
    public void EveryFileName_IsAPlainNameInsideTheIconFolder()
    {
        var escaping = Manifest.Value
            .Where(pair => pair.Value.Contains('/', StringComparison.Ordinal)
                || pair.Value.Contains('\\', StringComparison.Ordinal)
                || pair.Value.Contains("..", StringComparison.Ordinal)
                || string.IsNullOrWhiteSpace(pair.Value))
            .Select(pair => pair.Key)
            .ToList();

        Assert.Empty(escaping);
    }

    [Fact]
    public void EveryDivinationCard_ShareTheOneIcon()
    {
        // 392 of the 968 slugs are cards (00-api-contract.md §6.6). An exact count would have to be
        // edited every league; nought would mean the fallback stopped firing and two fifths of the
        // catalogue went blank, which is the regression worth catching.
        var cards = Manifest.Value.Values.Count(name => string.Equals(name, CardIcon, StringComparison.Ordinal));

        Assert.True(cards > 300, $"Only {cards} slug(s) map to {CardIcon}; the card fallback is not firing.");
        Assert.True(File.Exists(Path.Combine(IconDirectory, CardIcon)), $"{CardIcon} was not copied to the output.");
    }

    [Fact]
    public void TheManifestCoversExactlyTheSlugsTheKoreanDictionaryNames()
    {
        // Both files come out of the same join (00-api-contract.md §6.3) and are regenerated by the
        // same league refresh. Regenerating one and forgetting the other is the likely mistake, and
        // this is the assertion that notices — neither file alone can tell.
        var dictionary = Path.Combine(AppContext.BaseDirectory, "Localization", "ko.json");
        Assert.True(File.Exists(dictionary), $"ko.json was not copied to the output: {dictionary}");

        var korean = JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(dictionary));
        Assert.NotNull(korean);

        var named = korean!.Keys
            .Where(key => !key.StartsWith("ui.", StringComparison.Ordinal))
            .ToHashSet(StringComparer.Ordinal);

        var withIcons = Manifest.Value.Keys.ToHashSet(StringComparer.Ordinal);

        Assert.Empty(named.Except(withIcons).OrderBy(slug => slug, StringComparer.Ordinal));
        Assert.Empty(withIcons.Except(named).OrderBy(slug => slug, StringComparer.Ordinal));
    }
}
