using System.Text.Json.Serialization;

namespace PoeOverlay.Core.Catalog;

/// <summary>The wire shape of one catalogue row (S4 2.5 / <c>00-api-contract.md</c> §6.8).</summary>
/// <param name="Cat">An <c>ExchangeCategory</c> member name. Anything else costs that row.</param>
/// <param name="En">The English display name, which no dictionary carries — <c>en.json</c> is all <c>ui.*</c>.</param>
internal sealed record CatalogEntryDto(string? Cat, string? En);

/// <summary>
/// Source-generated serialisation for <c>item-catalog.json</c>.
/// </summary>
/// <remarks>
/// Case-sensitive on purpose, like every other context here: the file is generated by
/// <c>tools/build-item-catalog.py</c>, so a name that differs by case is a defect in the
/// generator rather than a spelling the reader should absorb.
/// </remarks>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(Dictionary<string, CatalogEntryDto>))]
internal sealed partial class CatalogJsonContext : JsonSerializerContext
{
}
